const demoData = [
  {
    key: '1',
    title: 'Channel 1',
    overview: 'Overview of Channel 1',
    streamPath: '/stream/1',
    logoPath: '/logo/1',
    status: 'active',
    category: 'movies',
    group: 'group1',
    createdAt: new Date(),
  },
  {
    key: '2',
    title: 'Channel 2',
    overview: 'Overview of Channel 2',
    streamPath: '/stream/2',
    logoPath: '/logo/2',
    status: 'inactive',
    category: 'sports',
    group: 'group2',
    createdAt: new Date(),
  },
  {
    key: '3',
    title: 'Channel 3',
    overview: 'Overview of Channel 3',
    streamPath: '/stream/3',
    logoPath: '/logo/3',
    status: 'active',
    category: 'news',
    group: 'group3',
    createdAt: new Date(),
  },
  {
    key: '4',
    title: 'Channel 4',
    overview: 'Overview of Channel 4',
    streamPath: '/stream/4',
    logoPath: '/logo/4',
    status: 'active',
    category: 'kids',
    group: 'group4',
    createdAt: new Date(),
  },
  {
    key: '5',
    title: 'Channel 5',
    overview: 'Overview of Channel 5',
    streamPath: '/stream/5',
    logoPath: '/logo/5',
    status: 'inactive',
    category: 'movies',
    group: 'group5',
    createdAt: new Date(),
  },
  {
    key: '6',
    title: 'Channel 6',
    overview: 'Overview of Channel 6',
    streamPath: '/stream/6',
    logoPath: '/logo/6',
    status: 'active',
    category: 'sports',
    group: 'group6',
    createdAt: new Date(),
  },
  {
    key: '7',
    title: 'Channel 7',
    overview: 'Overview of Channel 7',
    streamPath: '/stream/7',
    logoPath: '/logo/7',
    status: 'inactive',
    category: 'news',
    group: 'group7',
    createdAt: new Date(),
  },
  {
    key: '8',
    title: 'Channel 8',
    overview: 'Overview of Channel 8',
    streamPath: '/stream/8',
    logoPath: '/logo/8',
    status: 'active',
    category: 'kids',
    group: 'group8',
    createdAt: new Date(),
  },
  {
    key: '9',
    title: 'Channel 9',
    overview: 'Overview of Channel 9',
    streamPath: '/stream/9',
    logoPath: '/logo/9',
    status: 'inactive',
    category: 'movies',
    group: 'group9',
    createdAt: new Date(),
  },
  {
    key: '10',
    title: 'Channel 10',
    overview: 'Overview of Channel 10',
    streamPath: '/stream/10',
    logoPath: '/logo/10',
    status: 'active',
    category: 'sports',
    group: 'group10',
    createdAt: new Date(),
  },
  {
    key: '11',
    title: 'Channel 11',
    overview: 'Overview of Channel 11',
    streamPath: '/stream/11',
    logoPath: '/logo/11',
    status: 'active',
    category: 'news',
    group: 'group11',
    createdAt: new Date(),
  },
  {
    key: '12',
    title: 'Channel 12',
    overview: 'Overview of Channel 12',
    streamPath: '/stream/12',
    logoPath: '/logo/12',
    status: 'inactive',
    category: 'kids',
    group: 'group12',
    createdAt: new Date(),
  },
  {
    key: '13',
    title: 'Channel 13',
    overview: 'Overview of Channel 13',
    streamPath: '/stream/13',
    logoPath: '/logo/13',
    status: 'active',
    category: 'movies',
    group: 'group13',
    createdAt: new Date(),
  },
  {
    key: '14',
    title: 'Channel 14',
    overview: 'Overview of Channel 14',
    streamPath: '/stream/14',
    logoPath: '/logo/14',
    status: 'inactive',
    category: 'sports',
    group: 'group14',
    createdAt: new Date(),
  },
  {
    key: '15',
    title: 'Channel 15',
    overview: 'Overview of Channel 15',
    streamPath: '/stream/15',
    logoPath: '/logo/15',
    status: 'active',
    category: 'news',
    group: 'group15',
    createdAt: new Date(),
  },
  {
    key: '16',
    title: 'Channel 16',
    overview: 'Overview of Channel 16',
    streamPath: '/stream/16',
    logoPath: '/logo/16',
    status: 'inactive',
    category: 'kids',
    group: 'group16',
    createdAt: new Date(),
  },
  {
    key: '17',
    title: 'Channel 17',
    overview: 'Overview of Channel 17',
    streamPath: '/stream/17',
    logoPath: '/logo/17',
    status: 'active',
    category: 'movies',
    group: 'group17',
    createdAt: new Date(),
  },
  {
    key: '18',
    title: 'Channel 18',
    overview: 'Overview of Channel 18',
    streamPath: '/stream/18',
    logoPath: '/logo/18',
    status: 'inactive',
    category: 'sports',
    group: 'group18',
    createdAt: new Date(),
  },
  {
    key: '19',
    title: 'Channel 19',
    overview: 'Overview of Channel 19',
    streamPath: '/stream/19',
    logoPath: '/logo/19',
    status: 'active',
    category: 'news',
    group: 'group19',
    createdAt: new Date(),
  },
  {
    key: '20',
    title: 'Channel 20',
    overview: 'Overview of Channel 20',
    streamPath: '/stream/20',
    logoPath: '/logo/20',
    status: 'inactive',
    category: 'kids',
    group: 'group20',
    createdAt: new Date(),
  },
];

export default demoData;
